server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/api/teacher/**
          filters:
            - name: CircuitBreaker
              args:
                name: teacher-service
                fallbackUri: forward:/fallback/teacher-service

        - id: subject-service
          uri: lb://subject-service
          predicates:
            - Path=/api/subject/**
          filters:
            - name: CircuitBreaker
              args:
                name: subject-service
                fallbackUri: forward:/fallback/subject-service

        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/address/**
          filters:
            - name: CircuitBreaker
              args:
                name: address-service
                fallbackUri: forward:/fallback/address-service

  config:
      import: "optional:configserver:http://localhost:9196/"

